// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DaemonStatus() {
  return window['go']['main']['App']['DaemonStatus']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}
