// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DaemonStatus():Promise<main.DaemonStatusResult>;

export function Ping(arg1:string):Promise<string>;
