// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseQuickPrompt():Promise<void>;

export function DaemonStatus():Promise<main.DaemonStatusResult>;

export function HideOverlay():Promise<void>;

export function IsOverlay():Promise<boolean>;

export function LogFromFrontend(arg1:string):Promise<void>;

export function OpenQuickPrompt():Promise<void>;

export function Ping(arg1:string):Promise<string>;

export function ShowOverlay():Promise<void>;

export function ToggleQuickPrompt():Promise<void>;

export function ToggleOverlay():Promise<void>;
