"use client";

import { motion } from "motion/react";
import PageHeader from "@/components/shell/PageHeader";

const SECTIONS = [
  { id: "summary", title: "Summary", body: `Condura is designed from the ground up to respect your privacy. The software runs locally on your machine. We do not collect telemetry, usage statistics, or personal information. This policy explains what data the software accesses and how it is handled.` },
  { id: "data-local", title: "Data Stays Local", body: `All data generated by Condura — including conversation history, skills, audit logs, API keys, and configuration — is stored on your local machine. (Vector embeddings for semantic memory are on the v0.2.0 roadmap.) No data is transmitted to Condura Inc. or any third party unless you explicitly configure a cloud feature.` },
  { id: "api-keys", title: "API Keys", body: `API keys you provide for LLM providers (OpenAI, Anthropic, Google, etc.) are stored encrypted on your local machine using your operating system's keychain (macOS Keychain, Windows Credential Manager, libsecret on Linux). They are never logged, never sent to Condura Inc., and never included in any telemetry.` },
  { id: "network", title: "Network Requests", body: `The only network requests Condura makes are: (a) to the LLM provider(s) you explicitly configured, to fulfill your requests; (b) to check for software updates (configurable); and (c) to GitHub for release information when you visit the download page. We do not operate analytics servers, tracking pixels, or data-collection endpoints.` },
  { id: "cookies", title: "Cookies", body: `The condura.app website does not use cookies, tracking scripts, or any form of client-side storage for analytics or advertising. The site is statically generated and served without any third-party tracking.` },
  { id: "third-party", title: "Third-Party Services", body: `Condura integrates with third-party LLM providers at your direction. Each provider has its own privacy policy governing how it handles data you send through its API. Condura Inc. is not responsible for the data practices of these providers. We recommend reviewing their policies before use.` },
  { id: "changes", title: "Changes to This Policy", body: `If this policy changes materially, we will update the version date below and, for significant changes, notify you through the software. Continued use after changes take effect constitutes acceptance of the updated policy.` },
  { id: "contact", title: "Contact", body: `For questions about this privacy policy, contact privacy@condura.app.` },
];

export default function PrivacyPage() {
  return (
    <PageHeader
      eyebrow="Privacy"
      title="We don't"
      titleAccent="track you."
      description="No telemetry, no analytics, no cookies. Condura runs on your machine and stays there. This page explains exactly what that means."
    >
      <div className="mx-auto mt-8 max-w-3xl">
        <div className="space-y-14">
          {SECTIONS.map((section, i) => (
            <motion.section
              key={section.id}
              id={section.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-10%" }}
              transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
              className="scroll-mt-32"
            >
              <h2 className="font-display text-[26px] leading-tight text-[var(--color-ink)]">
                <span className="mr-4 font-mono text-[14px] text-[var(--color-synapse)]">
                  {String(i + 1).padStart(2, "0")}
                </span>
                {section.title}
              </h2>
              <p className="mt-5 pl-0 text-body leading-[1.75] text-[var(--color-ink-soft)] sm:pl-12">
                {section.body}
              </p>
            </motion.section>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4 }}
          className="mt-24 border-t border-[rgba(20,17,11,0.12)] pt-8 text-center"
        >
          <p className="text-small text-[var(--color-ink-faint)]">
            Last updated June 2026 · Condura Inc.
          </p>
        </motion.div>
      </div>
    </PageHeader>
  );
}
