"use client";

import PageChrome from "@/components/shell/PageChrome";
import { motion } from "motion/react";

const SECTIONS = [
  {
    id: "summary",
    title: "Summary",
    body: `Condura is designed from the ground up to respect your privacy. The software runs locally on your machine. We do not collect telemetry, usage statistics, or personal information. This policy explains what data the software accesses and how it is handled.`,
  },
  {
    id: "data-local",
    title: "Data Stays Local",
    body: `All data generated by Condura — including conversation history, vector embeddings, skills, audit logs, API keys, and configuration — is stored on your local machine. No data is transmitted to Condura Inc. or any third party unless you explicitly configure a cloud feature.`,
  },
  {
    id: "api-keys",
    title: "API Keys",
    body: `API keys you provide for LLM providers (OpenAI, Anthropic, Google, etc.) are stored encrypted on your local machine using your operating system's keychain (macOS Keychain, Windows Credential Manager, libsecret on Linux). They are never logged, never sent to Condura Inc., and never included in any telemetry.`,
  },
  {
    id: "network",
    title: "Network Requests",
    body: `The only network requests Condura makes are: (a) to the LLM provider(s) you explicitly configured, to fulfill your requests; (b) to check for software updates (configurable); and (c) to GitHub for release information when you visit the download page. We do not operate analytics servers, tracking pixels, or data-collection endpoints.`,
  },
  {
    id: "cookies",
    title: "Cookies",
    body: `The condura.app website does not use cookies, tracking scripts, or any form of client-side storage for analytics or advertising. The site is statically generated and served without any third-party tracking.`,
  },
  {
    id: "third-party",
    title: "Third-Party Services",
    body: `Condura integrates with third-party LLM providers at your direction. Each provider has its own privacy policy governing how it handles data you send through its API. Condura Inc. is not responsible for the data practices of these providers. We recommend reviewing their policies before use.`,
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    body: `If this policy changes materially, we will update the version date below and, for significant changes, notify you through the software. Continued use after changes take effect constitutes acceptance of the updated policy.`,
  },
  {
    id: "contact",
    title: "Contact",
    body: `For questions about this privacy policy, contact legal@condura.app.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="bg-black text-white min-h-screen">
      <PageChrome
        eyebrow="Privacy"
        title="We don't track you."
        description="No telemetry, no analytics, no cookies. Condura runs on your machine and stays there. This page explains exactly what that means."
        badge="Policy"
      >
        <div className="mt-24 max-w-4xl mx-auto">
          <div className="space-y-16">
            {SECTIONS.map((section, i) => (
              <motion.section
                key={section.id}
                id={section.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08, duration: 0.6 }}
              >
                <h2 className="text-2xl font-medium mb-6 text-white">
                  <span className="text-white/30 font-mono text-sm mr-4">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  {section.title}
                </h2>
                <p className="text-white/70 text-[17px] leading-relaxed pl-12">
                  {section.body}
                </p>
              </motion.section>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.2 }}
            className="mt-24 pt-8 border-t border-white/10 text-center"
          >
            <p className="text-sm text-white/30">
              Last updated June 2026 · Condura Inc.
            </p>
          </motion.div>
        </div>
      </PageChrome>
    </div>
  );
}
